import toKeyValue from '../toKeyValue'

/**
 * Returns an array containing local and global classnames based on the given styles object and globalKey
 * @param {Object} styles - The styles object, most likely generated by css modules
 * @param {string} globalKey - The global key, or global classname
 * @returns {Array} - Returns an array of two strings: [localClassname, globalClassname]
 */
export default function createGlobalLocalClassnames(styles, globalKey) {
    const { key: globalClassname, value: localClassname } = toKeyValue(globalKey, styles)
    return [localClassname, globalClassname]
}
